In [45]:
from discovery_child_development.getters import gtr
import pandas as pd

import datetime

import importlib
importlib.reload(gtr);

from discovery_child_development import PROJECT_DIR
ENRICHED_DATA_DIR = PROJECT_DIR / 'outputs/enrichments'

In [7]:
projects_df = gtr.get_gtr_from_s3(table='projects')

In [40]:
funds_dict = gtr.get_gtr_from_s3(table='funds')

In [19]:
projects_df[0].keys()

dict_keys(['links', 'id', 'href', 'created', 'identifiers', 'title', 'status', 'grantCategory', 'leadFunder', 'leadOrganisationDepartment', 'abstractText', 'techAbstractText', 'healthCategories', 'researchActivities', 'researchSubjects', 'researchTopics', 'rcukProgrammes'])

In [104]:
funds_id = []
start = []
ends = []
value = []
currencies = []

for funds in funds_dict:
    funds_id.append(funds['id'])
    start.append(funds['start'])
    ends.append(funds['end'])
    value.append(funds['valuePounds']['amount'] if 'valuePounds' in funds else None)
    currencies.append(funds['valuePounds']['currencyCode'] if 'valuePounds' in funds else None)

funds_df = (
    pd.DataFrame({'funds_id': funds_id, 'start': start, 'ends': ends, 'amount': value, 'currency': currencies})
    .assign(start = lambda df: df.start.apply(lambda x: datetime.datetime.fromtimestamp(int(x)/1000).strftime('%Y-%m-%d')))
    .assign(ends = lambda df: df.ends.apply(lambda x: datetime.datetime.fromtimestamp(int(x)/1000).strftime('%Y-%m-%d')))
)

In [105]:
funds_df.head(1)

,funds_id,start,ends,amount,currency
0,2293906D-CC22-4E09-A91E-CE2CC6FE6CCD,2022-08-01,2026-07-31,1529795,GBP

In [108]:
ids = []
titles = []
abstracts = []
tech_abstracts = []
starts = []
ends = []
funds_id = []

for project in projects_df:
    ids.append(project['id'])
    titles.append(project['title']) if 'title' in project.keys() else titles.append('')
    abstracts.append(project['abstractText']) if 'abstractText' in project.keys() else abstracts.append('')
    tech_abstracts.append(project['techAbstractText']) if 'techAbstractText' in project.keys() else tech_abstracts.append('')

    funds = [l for l in project['links']['link'] if l['rel'] == "FUND"][0]
    starts.append(datetime.datetime.fromtimestamp(int(funds['start'])/1000).strftime('%Y-%m-%d'))
    ends.append(datetime.datetime.fromtimestamp(int(funds['end'])/1000).strftime('%Y-%m-%d'))
    funds_id.append(funds['href'].split('/')[-1])

gtr_texts_df = (
    pd.DataFrame({
        'id': ids,
        'title': titles,
        'abstract': abstracts,
        'tech_abstract': tech_abstracts,
        'start': starts,
        "end": ends,
        "funds_id": funds_id,
    })
    .assign(text = lambda x: x['title'] + '. ' + x['abstract'] + '. ' + x['tech_abstract'])
    .merge(funds_df[['funds_id', 'amount', 'currency']], on='funds_id', how='left', suffixes=('', '_funds'))
)

In [109]:
gtr_texts_df.head(10)

,id,title,abstract,tech_abstract,start,end,funds_id,text,amount,currency
0,9FCC3406-8050-4D4B-A4D6-14ABC3A9AC51,20-BBSRC/NSF-BIO Regulatory control of innate immune response in marine invertebrates,"Animals live in constantly changing environments that are rich in microbial life. Immune systems orchestrate the complex, dynamic relationships between animals and microbes by both eliminating pathogenic microbes as well as promoting the growth of beneficial microbiota. However, our understanding of innate immune mechanisms in most animal phyla, including vertebrates, remains limited. The proposed research addresses this considerable knowledge gap by exploiting the experimental advantages of echinoderm larvae to investigate immune responses in a relatively unexplored animal lineage. Echinoderm larvae are morphologically simple, free-swimming multicellular organisms equipped with a sophisticated cellular and molecular immune system. By integrating recently available sequencing data from several echinoderm species with technology for measuring gene expression at single-cell resolution, the proposed research will significantly advance our understanding of animal immunity. This proposa...","Animals live in constantly changing environments that are rich in microbial life. Immune systems orchestrate the complex, dynamic relationships between animals and microbes by both eliminating pathogenic microbes as well as promoting the growth of beneficial microbiota. However, our understanding of innate immune mechanisms in most animal phyla remains limited. The proposed research will address this knowledge gap by exploiting the experimental advantages of echinoderm larvae to investigate immune responses.\nThe proposed work will investigate immunity in four echinoderm species and characterising the response to both bacterial and viral pathogens. The echinoderm species were selected to reflect a range of taxonomic distances, ecological niches, and life history traits. The proposed work will be carried out in three aims. First, larval immune cell populations will be defined using in vivo microscopy and functional assays. Second, the change in gene activity in response to immune ch...",2022-01-01,2024-12-31,8146E9B5-D152-4584-8B7A-061CAF34D028,"20-BBSRC/NSF-BIO Regulatory control of innate immune response in marine invertebrates. Animals live in constantly changing environments that are rich in microbial life. Immune systems orchestrate the complex, dynamic relationships between animals and microbes by both eliminating pathogenic microbes as well as promoting the growth of beneficial microbiota. However, our understanding of innate immune mechanisms in most animal phyla, including vertebrates, remains limited. The proposed research addresses this considerable knowledge gap by exploiting the experimental advantages of echinoderm larvae to investigate immune responses in a relatively unexplored animal lineage. Echinoderm larvae are morphologically simple, free-swimming multicellular organisms equipped with a sophisticated cellular and molecular immune system. By integrating recently available sequencing data from several echinoderm species with technology for measuring gene expression at single-cell resolution, the proposed...",513195,GBP
1,A0987686-9E04-4618-8588-162133A29DB8,Design and development of a Virtual Standardised Patient platform for improving medical training,"Abstracts are not currently available in GtR for all funded research. This is normally because the abstract was not required at the time of proposal submission, but may be because it included sensitive information such as personal details.",,2020-01-01,2021-06-30,BE7A902A-33CA-4FCF-844B-BCE32EC53DC9,"Design and development of a Virtual Standardised Patient platform for improving medical training. Abstracts are not currently available in GtR for all funded research. This is normally because the abstract was not required at the time of proposal submission, but may be because it included sensitive information such as personal details..",149991,GBP
2,A19F3F57-5171-4446-8776-13E3E37FB124,RMISTCR - Rapidly mining the immune system for rare therapeutic T-Cell Receptors to treat solid tumour cancers,"**Need**\n\nAccording to Cancer Research UK, ~367,000 new cancer cases are diagnosed every year in the UK. Cancer kills 165,000 people each year in the UK. There is the urgent need for &quot;new curative treatments for solid tumour cancer... cheaply and effectively&quot; (NHS-Long Term Plan).\n\n**Challenge**\n\nT-cell-receptor-based cell therapies are promising curative treatments for otherwise untreatable advanced solid tumours. Consisting of immune cells known as T-cells, they are derived from patients, then genetically reprogrammed with a cancer-targeting T-cell receptor (TCR), before being multiplied, and reintroduced into patients to destroy cancer cells.\n\nUnfortunately finding these curative TCRs is a needle in a haystack problem and a major challenge using existing technologies in the lab such as mammalian display, which has an average discovery time of ~6 years and costs \\\&gt;&pound;10million/biopsy. There is an urgent need for computational methods to automate and str...",,2023-10-01,2024-12-31,A091EDBB-8EB5-45F4-96F3-510A1219CA1A,"RMISTCR - Rapidly mining the immune system for rare therapeutic T-Cell Receptors to treat solid tumour cancers. **Need**\n\nAccording to Cancer Research UK, ~367,000 new cancer cases are diagnosed every year in the UK. Cancer kills 165,000 people each year in the UK. There is the urgent need for &quot;new curative treatments for solid tumour cancer... cheaply and effectively&quot; (NHS-Long Term Plan).\n\n**Challenge**\n\nT-cell-receptor-based cell therapies are promising curative treatments for otherwise untreatable advanced solid tumours. Consisting of immune cells known as T-cells, they are derived from patients, then genetically reprogrammed with a cancer-targeting T-cell receptor (TCR), before being multiplied, and reintroduced into patients to destroy cancer cells.\n\nUnfortunately finding these curative TCRs is a needle in a haystack problem and a major challenge using existing technologies in the lab such as mammalian display, which has an average discovery time of ~6 years...",469216,GBP
3,516377E5-767C-48BD-B60F-15948D11A117,Fluctuation Induced Exotic Phases of Quantum Matter,"Usually fluctuations have a destabilising effect. When carrying a tray of drinks through a crowded room one wishes to avoid the jostling of the crowd. Similarly, a tightrope walker would probably avoid performing on a blustery day. \n\nHowever, there are many instances where fluctuations can have the opposite effect, stabilising a system in a configuration that might otherwise be unstable. This occurs when the noise is state-dependent; that is, when the spectrum of the fluctuating forces experienced by the system is modified by the particular configuration of the system. Examples include the balancing of a broom on ones fingertip - practice leads the expert to approach ever more closely to a Levy flight distribution of horizontal movements. The crucial point is that the torque experienced by the broom depends upon its angle to the vertical. Many other examples may be viewed in this way. For example, adaptable species, agile businesses and diverse investment strategies are all stabl...",,2017-04-01,2021-09-30,CEF26646-3DA7-412E-9487-74F8F6D2964C,"Fluctuation Induced Exotic Phases of Quantum Matter. Usually fluctuations have a destabilising effect. When carrying a tray of drinks through a crowded room one wishes to avoid the jostling of the crowd. Similarly, a tightrope walker would probably avoid performing on a blustery day. \n\nHowever, there are many instances where fluctuations can have the opposite effect, stabilising a system in a configuration that might otherwise be unstable. This occurs when the noise is state-dependent; that is, when the spectrum of the fluctuating forces experienced by the system is modified by the particular configuration of the system. Examples include the balancing of a broom on ones fingertip - practice leads the expert to approach ever more closely to a Levy flight distribution of horizontal movements. The crucial point is that the torque experienced by the broom depends upon its angle to the vertical. Many other examples may be viewed in this way. For example, adaptable species, agile busin...",735282,GBP
4,52DBD630-CDDC-466E-AAA9-149006D9ADDC,Modelling of Beam Dynamics for the New Muon g-2 Experiment at FNAL,"Measurements of the anomalous magnetic moment (g-2) of the muon have indicated a small difference from the value predicted by the Standard Model of particle physics: any difference would indicate the existence of new physics. However, the precision of existing measurements is not sufficient to confirm a discrepancy between theory and measurement with any certainty. A new experiment, presently under construction at Fermilab, aims to improve the measurement precision of the muon g-2 by at least a factor of four over previous measurements. This will establish with confidence whether or not there is a significant difference between the measured and theoretical values.\nThe anomalous magnetic moment of the muon is measured by observing the spin precession of a bunch of muons as they move through a uniform magnetic field in a storage ring. The precision of the measurement depends critically on a detailed understanding of the properties of the particles as they are injected into the stora...",,2015-10-01,2019-03-31,EBEB2831-EDFF-4037-8908-CAE7D7029418,"Modelling of Beam Dynamics for the New Muon g-2 Experiment at FNAL. Measurements of the anomalous magnetic moment (g-2) of the muon have indicated a small difference from the value predicted by the Standard Model of particle physics: any difference would indicate the existence of new physics. However, the precision of existing measurements is not sufficient to confirm a discrepancy between theory and measurement with any certainty. A new experiment, presently under construction at Fermilab, aims to improve the measurement precision of the muon g-2 by at least a factor of four over previous measurements. This will establish with confidence whether or not there is a significant difference between the measured and theoretical values.\nThe anomalous magnetic moment of the muon is measured by observing the spin precession of a bunch of muons as they move through a uniform magnetic field in a storage ring. The precision of the measurement depends critically on a detailed understanding of...",0,GBP
5,53610631-0E80-4508-A009-144067444802,Indicators of regime shifts in freshwater ecosystems,"Regime shifts, characterised by sudden, often irreversible, changes in the composition of biological communities, can have catastrophic impacts on the ecosystem services which society relies on. Classic examples of this phenomenon originate from freshwater ecosystems, where shifts in the structure of a community can lead to cyanobacteria-dominated ecosystems, with potential negative impacts on human and livestock health. Being able to predict impending regime shifts in time to avert them is consequently a critical goal with significant implications for the management of scarce freshwater resources. This project will use long-term monitoring data in combination with advanced modelling techniques to characterise how community composition can change prior to and during a regime shift, and test and develop generalisable methods to predict and prevent such shifts in the future. A key goal in predictive ecology is forecasting the potential for rapid changes in ecosystems, leading to the ...",,2020-10-01,2024-04-01,AABAD45E-9387-4894-8C50-616533A008D8,"Indicators of regime shifts in freshwater ecosystems. Regime shifts, characterised by sudden, often irreversible, changes in the composition of biological communities, can have catastrophic impacts on the ecosystem services which society relies on. Classic examples of this phenomenon originate from freshwater ecosystems, where shifts in the structure of a community can lead to cyanobacteria-dominated ecosystems, with potential negative impacts on human and livestock health. Being able to predict impending regime shifts in time to avert them is consequently a critical goal with significant implications for the management of scarce freshwater resources. This project will use long-term monitoring data in combination with advanced modelling techniques to characterise how community composition can change prior to and during a regime shift, and test and develop generalisable methods to predict and prevent such shifts in the future. A key goal in predictive ecology is forecasting the pote...",0,GBP
6,53CCDC2D-75DF-4A34-8C2C-1504DBFFF12D,Housing in a Hostile Environment: A Critical Study of the Provision of Asylum Seeker Housing under the COMPASS Contracts and its Effects on Subjecthoo,"This project will explore the complexities of the UK Home Office's COMPASS contract for asylum seeker housing provision in Scotland at a crucial juncture in the contract's lifespan. It will build upon work investigating the UK Government's implementation of border regimes in housing legislation and policy by Crawford et al., 2016, Leahy et al 2018 and the wholesale privatization of asylum seeker housing through the COMPASS[1] contracts by Darling, 2016a, 2016b. My research will critically examine the contracting of the care of vulnerable persons to private corporations, specifically the impact of this contract upon the frontline staff who enact it and the asylum seekers who live under it. This will be undertaken through a critical examination of legislation, policy and contract documents, as well as semi-structured interviews with housing provider staff and asylum-seeking residents in Scotland.\n \nThe project will be of particular significance for the academic disciplines of migra...",,2019-10-01,2023-09-30,3D9563CC-9AA4-45BE-99C9-B940FEA9E9AD,"Housing in a Hostile Environment: A Critical Study of the Provision of Asylum Seeker Housing under the COMPASS Contracts and its Effects on Subjecthoo. This project will explore the complexities of the UK Home Office's COMPASS contract for asylum seeker housing provision in Scotland at a crucial juncture in the contract's lifespan. It will build upon work investigating the UK Government's implementation of border regimes in housing legislation and policy by Crawford et al., 2016, Leahy et al 2018 and the wholesale privatization of asylum seeker housing through the COMPASS[1] contracts by Darling, 2016a, 2016b. My research will critically examine the contracting of the care of vulnerable persons to private corporations, specifically the impact of this contract upon the frontline staff who enact it and the asylum seekers who live under it. This will be undertaken through a critical examination of legislation, policy and contract documents, as well as semi-structured interviews with h...",0,GBP
7,546D368D-BA8B-43B4-9367-14812BD0C86C,Satsims Business Sprint,"Development of enabling technologies, exploiting satellite data for games, serious games and simulations.",,2014-11-01,2015-04-30,BFE5F2F0-5D08-4309-86F7-00A9E995E105,"Satsims Business Sprint. Development of enabling technologies, exploiting satellite data for games, serious games and simulations..",5000,GBP
8,353CB253-F8CD-4FF2-A2F1-1532D944C76E,Advanced non-invasive imaging biomarker for use in drug trials,no public description,,2020-06-01,2021-02-28,400AF7C2-A3AB-42E8-828C-F527AB7BF266,Advanced non-invasive imaging biomarker for use in drug trials. no public description.,116070,GBP
9,35660A19-61BA-46B1-A85D-15A6C5629E8F,'Women's Style' and American Independent Cinema: Gender Politics and Women Film Directors,"American cinema is often highly gendered for women directors, yet de-gendered for male directors. The gender of male directors is rarely referenced in either academic or popular writing, yet is frequently evoked when discussing women directors. By highlighting the gender of women directors or suggesting that women directors make 'women's films', there is an argument that can be made that these films have an audience and set of formal expectations that are gender specific. This research aims to assess how this gendered discourse effects the opportunities for women directors in American independent cinema as well as the reception of their films. Scholars such as King (2005) and Levy (1999) suggest that American independent cinema offers greater accessibility to filmmaking than mainstream cinema, yet according to the Centre for the Study of Women in Television and Film at San Diego State University, just 29% of the top 100 American independent features of 2016-17 were directed by wome...",,2018-10-01,2021-12-31,177A3B7E-9A89-46B6-8BBC-ABB61004C179,"'Women's Style' and American Independent Cinema: Gender Politics and Women Film Directors. American cinema is often highly gendered for women directors, yet de-gendered for male directors. The gender of male directors is rarely referenced in either academic or popular writing, yet is frequently evoked when discussing women directors. By highlighting the gender of women directors or suggesting that women directors make 'women's films', there is an argument that can be made that these films have an audience and set of formal expectations that are gender specific. This research aims to assess how this gendered discourse effects the opportunities for women directors in American independent cinema as well as the reception of their films. Scholars such as King (2005) and Levy (1999) suggest that American independent cinema offers greater accessibility to filmmaking than mainstream cinema, yet according to the Centre for the Study of Women in Television and Film at San Diego State Univers...",0,GBP

In [114]:
gtr_texts_df.drop(['abstract', 'tech_abstract'], axis=1).query("start >= '2013-01-01'").to_csv(ENRICHED_DATA_DIR / 'gtr_texts.csv', index=False)

In [112]:
gtr_texts_df.head(5)

,id,title,abstract,tech_abstract,start,end,funds_id,text,amount,currency
0,9FCC3406-8050-4D4B-A4D6-14ABC3A9AC51,20-BBSRC/NSF-BIO Regulatory control of innate immune response in marine invertebrates,"Animals live in constantly changing environments that are rich in microbial life. Immune systems orchestrate the complex, dynamic relationships between animals and microbes by both eliminating pathogenic microbes as well as promoting the growth of beneficial microbiota. However, our understanding of innate immune mechanisms in most animal phyla, including vertebrates, remains limited. The proposed research addresses this considerable knowledge gap by exploiting the experimental advantages of echinoderm larvae to investigate immune responses in a relatively unexplored animal lineage. Echinoderm larvae are morphologically simple, free-swimming multicellular organisms equipped with a sophisticated cellular and molecular immune system. By integrating recently available sequencing data from several echinoderm species with technology for measuring gene expression at single-cell resolution, the proposed research will significantly advance our understanding of animal immunity. This proposa...","Animals live in constantly changing environments that are rich in microbial life. Immune systems orchestrate the complex, dynamic relationships between animals and microbes by both eliminating pathogenic microbes as well as promoting the growth of beneficial microbiota. However, our understanding of innate immune mechanisms in most animal phyla remains limited. The proposed research will address this knowledge gap by exploiting the experimental advantages of echinoderm larvae to investigate immune responses.\nThe proposed work will investigate immunity in four echinoderm species and characterising the response to both bacterial and viral pathogens. The echinoderm species were selected to reflect a range of taxonomic distances, ecological niches, and life history traits. The proposed work will be carried out in three aims. First, larval immune cell populations will be defined using in vivo microscopy and functional assays. Second, the change in gene activity in response to immune ch...",2022-01-01,2024-12-31,8146E9B5-D152-4584-8B7A-061CAF34D028,"20-BBSRC/NSF-BIO Regulatory control of innate immune response in marine invertebrates. Animals live in constantly changing environments that are rich in microbial life. Immune systems orchestrate the complex, dynamic relationships between animals and microbes by both eliminating pathogenic microbes as well as promoting the growth of beneficial microbiota. However, our understanding of innate immune mechanisms in most animal phyla, including vertebrates, remains limited. The proposed research addresses this considerable knowledge gap by exploiting the experimental advantages of echinoderm larvae to investigate immune responses in a relatively unexplored animal lineage. Echinoderm larvae are morphologically simple, free-swimming multicellular organisms equipped with a sophisticated cellular and molecular immune system. By integrating recently available sequencing data from several echinoderm species with technology for measuring gene expression at single-cell resolution, the proposed...",513195,GBP
1,A0987686-9E04-4618-8588-162133A29DB8,Design and development of a Virtual Standardised Patient platform for improving medical training,"Abstracts are not currently available in GtR for all funded research. This is normally because the abstract was not required at the time of proposal submission, but may be because it included sensitive information such as personal details.",,2020-01-01,2021-06-30,BE7A902A-33CA-4FCF-844B-BCE32EC53DC9,"Design and development of a Virtual Standardised Patient platform for improving medical training. Abstracts are not currently available in GtR for all funded research. This is normally because the abstract was not required at the time of proposal submission, but may be because it included sensitive information such as personal details..",149991,GBP
2,A19F3F57-5171-4446-8776-13E3E37FB124,RMISTCR - Rapidly mining the immune system for rare therapeutic T-Cell Receptors to treat solid tumour cancers,"**Need**\n\nAccording to Cancer Research UK, ~367,000 new cancer cases are diagnosed every year in the UK. Cancer kills 165,000 people each year in the UK. There is the urgent need for &quot;new curative treatments for solid tumour cancer... cheaply and effectively&quot; (NHS-Long Term Plan).\n\n**Challenge**\n\nT-cell-receptor-based cell therapies are promising curative treatments for otherwise untreatable advanced solid tumours. Consisting of immune cells known as T-cells, they are derived from patients, then genetically reprogrammed with a cancer-targeting T-cell receptor (TCR), before being multiplied, and reintroduced into patients to destroy cancer cells.\n\nUnfortunately finding these curative TCRs is a needle in a haystack problem and a major challenge using existing technologies in the lab such as mammalian display, which has an average discovery time of ~6 years and costs \\\&gt;&pound;10million/biopsy. There is an urgent need for computational methods to automate and str...",,2023-10-01,2024-12-31,A091EDBB-8EB5-45F4-96F3-510A1219CA1A,"RMISTCR - Rapidly mining the immune system for rare therapeutic T-Cell Receptors to treat solid tumour cancers. **Need**\n\nAccording to Cancer Research UK, ~367,000 new cancer cases are diagnosed every year in the UK. Cancer kills 165,000 people each year in the UK. There is the urgent need for &quot;new curative treatments for solid tumour cancer... cheaply and effectively&quot; (NHS-Long Term Plan).\n\n**Challenge**\n\nT-cell-receptor-based cell therapies are promising curative treatments for otherwise untreatable advanced solid tumours. Consisting of immune cells known as T-cells, they are derived from patients, then genetically reprogrammed with a cancer-targeting T-cell receptor (TCR), before being multiplied, and reintroduced into patients to destroy cancer cells.\n\nUnfortunately finding these curative TCRs is a needle in a haystack problem and a major challenge using existing technologies in the lab such as mammalian display, which has an average discovery time of ~6 years...",469216,GBP
3,516377E5-767C-48BD-B60F-15948D11A117,Fluctuation Induced Exotic Phases of Quantum Matter,"Usually fluctuations have a destabilising effect. When carrying a tray of drinks through a crowded room one wishes to avoid the jostling of the crowd. Similarly, a tightrope walker would probably avoid performing on a blustery day. \n\nHowever, there are many instances where fluctuations can have the opposite effect, stabilising a system in a configuration that might otherwise be unstable. This occurs when the noise is state-dependent; that is, when the spectrum of the fluctuating forces experienced by the system is modified by the particular configuration of the system. Examples include the balancing of a broom on ones fingertip - practice leads the expert to approach ever more closely to a Levy flight distribution of horizontal movements. The crucial point is that the torque experienced by the broom depends upon its angle to the vertical. Many other examples may be viewed in this way. For example, adaptable species, agile businesses and diverse investment strategies are all stabl...",,2017-04-01,2021-09-30,CEF26646-3DA7-412E-9487-74F8F6D2964C,"Fluctuation Induced Exotic Phases of Quantum Matter. Usually fluctuations have a destabilising effect. When carrying a tray of drinks through a crowded room one wishes to avoid the jostling of the crowd. Similarly, a tightrope walker would probably avoid performing on a blustery day. \n\nHowever, there are many instances where fluctuations can have the opposite effect, stabilising a system in a configuration that might otherwise be unstable. This occurs when the noise is state-dependent; that is, when the spectrum of the fluctuating forces experienced by the system is modified by the particular configuration of the system. Examples include the balancing of a broom on ones fingertip - practice leads the expert to approach ever more closely to a Levy flight distribution of horizontal movements. The crucial point is that the torque experienced by the broom depends upon its angle to the vertical. Many other examples may be viewed in this way. For example, adaptable species, agile busin...",735282,GBP
4,52DBD630-CDDC-466E-AAA9-149006D9ADDC,Modelling of Beam Dynamics for the New Muon g-2 Experiment at FNAL,"Measurements of the anomalous magnetic moment (g-2) of the muon have indicated a small difference from the value predicted by the Standard Model of particle physics: any difference would indicate the existence of new physics. However, the precision of existing measurements is not sufficient to confirm a discrepancy between theory and measurement with any certainty. A new experiment, presently under construction at Fermilab, aims to improve the measurement precision of the muon g-2 by at least a factor of four over previous measurements. This will establish with confidence whether or not there is a significant difference between the measured and theoretical values.\nThe anomalous magnetic moment of the muon is measured by observing the spin precession of a bunch of muons as they move through a uniform magnetic field in a storage ring. The precision of the measurement depends critically on a detailed understanding of the properties of the particles as they are injected into the stora...",,2015-10-01,2019-03-31,EBEB2831-EDFF-4037-8908-CAE7D7029418,"Modelling of Beam Dynamics for the New Muon g-2 Experiment at FNAL. Measurements of the anomalous magnetic moment (g-2) of the muon have indicated a small difference from the value predicted by the Standard Model of particle physics: any difference would indicate the existence of new physics. However, the precision of existing measurements is not sufficient to confirm a discrepancy between theory and measurement with any certainty. A new experiment, presently under construction at Fermilab, aims to improve the measurement precision of the muon g-2 by at least a factor of four over previous measurements. This will establish with confidence whether or not there is a significant difference between the measured and theoretical values.\nThe anomalous magnetic moment of the muon is measured by observing the spin precession of a bunch of muons as they move through a uniform magnetic field in a storage ring. The precision of the measurement depends critically on a detailed understanding of...",0,GBP

## Check relevant gtr texts

In [88]:
from nesta_ds_utils.loading_saving import S3
from discovery_child_development import S3_BUCKET

In [89]:
gtr_texts_relevant_df = S3.download_obj(S3_BUCKET, f"data/outputs/binary_classifier/gtr_texts_relevance_labelled.csv", "dataframe")

In [94]:
gtr_texts_relevant_df.head(1)

,Unnamed: 0,id,start,end,text,predictions
0,0,9FCC3406-8050-4D4B-A4D6-14ABC3A9AC51,2022-01-01,2024-12-31,"20-BBSRC/NSF-BIO Regulatory control of innate immune response in marine invertebrates. Animals live in constantly changing environments that are rich in microbial life. Immune systems orchestrate the complex, dynamic relationships between animals and microbes by both eliminating pathogenic microbes as well as promoting the growth of beneficial microbiota. However, our understanding of innate immune mechanisms in most animal phyla, including vertebrates, remains limited. The proposed research addresses this considerable knowledge gap by exploiting the experimental advantages of echinoderm larvae to investigate immune responses in a relatively unexplored animal lineage. Echinoderm larvae are morphologically simple, free-swimming multicellular organisms equipped with a sophisticated cellular and molecular immune system. By integrating recently available sequencing data from several echinoderm species with technology for measuring gene expression at single-cell resolution, the proposed...",0

In [93]:
pd.set_option("max_colwidth", 1000)
gtr_texts_relevant_df.query("predictions == 1").to_csv(ENRICHED_DATA_DIR / 'gtr_texts_relevant.csv', index=False)