In [1]:
from discovery_child_development.getters import patents, openalex

2024-05-31 12:28:06,733 - botocore.credentials - INFO - Found credentials in environment variables.
2024-05-31 12:28:07,950 - datasets - INFO - PyTorch version 2.1.2 available.

/opt/homebrew/Caskroom/miniconda/base/envs/discovery_child_development/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## OpenAlex checking

In [10]:
latest_df = openalex.get_abstracts(input_path = 'data/openAlex/openalex_works_concepts_20240531_125353/')

In [3]:
old_df = openalex.get_abstracts(input_path = 'data/openAlex/openalex_works_concepts_20240229_105641/')

In [11]:
len(latest_df), len(old_df)

(158252, 116350)

In [225]:
text = 'Results From a Controlled Study of the iPad Fractions Game Motion Mat'
old_df[old_df.title.str.contains(text)]

Empty DataFrame
Columns: [id, title, abstract, text]
Index: []

In [226]:
latest_df[latest_df.title.str.contains(text)]

Empty DataFrame
Columns: [id, title, abstract, text]
Index: []

In [20]:
latest_df

,id,title,abstract,text
0,https://openalex.org/W2146349261,The impact of pretend play on children's devel...,Pretend play has been claimed to be crucial to...,The impact of pretend play on children's devel...
1,https://openalex.org/W2134744704,The Effects of Poverty on Childhood Brain Deve...,IMPORTANCE The study provides novel data to in...,The Effects of Poverty on Childhood Brain Deve...
2,https://openalex.org/W2124222455,Investing in Preschool Programs,We summarize the available evidence on the ext...,Investing in Preschool Programs. We summarize ...
3,https://openalex.org/W1993392684,Developmental Changes in Executive Functioning,Although early studies of executive functionin...,Developmental Changes in Executive Functioning...
4,https://openalex.org/W2022384642,Evidence for General and Domain‐Specific Eleme...,This study evaluates a model for considering d...,Evidence for General and Domain‐Specific Eleme...
...,...,...,...,...
191551,https://openalex.org/W2084542952,Prognosis and therapy of myasthenia gravis in ...,Objectives: To investigate the influence of on...,Prognosis and therapy of myasthenia gravis in ...
191553,https://openalex.org/W3163075822,Diarrea crónica en el niño,Prolongued diarrhea is defined as the increase...,Diarrea crónica en el niño. Prolongued diarrhe...
191554,https://openalex.org/W4252040904,Nonstarch Polysaccharides from Food Grains: ei...,Plant carbohydrates can be broadly classied in...,Nonstarch Polysaccharides from Food Grains: ei...
191556,https://openalex.org/W4251755310,Presidential lectureSpecial lectureEducational...,会長講演 第 1 日／第 1 会場／10：40～11：40 司会 里宇 明元 活動の臨床とし...,Presidential lectureSpecial lectureEducational...
191557,https://openalex.org/W2999641442,Wala Tayong Sasantuhin,Although downloading and printing of the artic...,Wala Tayong Sasantuhin. Although downloading a...

In [263]:
import requests

BASE_URL = "https://api.openalex.org/works"
BASE_KEYWORD = "(child)"
KEYWORDS_DATA = "(math app OR math apps)"
# QUERY = f'{BASE_URL}?search=(abstract:{KEYWORDS_DATA} AND abstract:{BASE_KEYWORD}) OR (title:
# {KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
QUERY = f'{BASE_URL}?search=(title:{KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
response = requests.get(f"{QUERY}&per-page=100")
j=-1
response.json()['meta']

{'count': 1355,
 'db_response_time_ms': 244,
 'page': 1,
 'per_page': 100,
 'groups_count': None}

In [266]:
j+=1
_id = response.json()['results'][j]['id']
print(_id)
print(response.json()['results'][j]['publication_year'])
print(response.json()['results'][j]['title'])

https://openalex.org/W1041173458
2015
Tablet use in schools: a critical review of the evidence for learning outcomes

In [258]:
BASE_KEYWORD = "(child)"
KEYWORDS_DATA = "('math app' OR 'math apps')"
# QUERY = f'{BASE_URL}?search=(abstract:{KEYWORDS_DATA} AND abstract:{BASE_KEYWORD}) OR (title:{KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
QUERY = f'{BASE_URL}?search=(title:{KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
response = requests.get(f"{QUERY}&per-page=100")
j=-1
response.json()['meta']

{'count': 1355,
 'db_response_time_ms': 130,
 'page': 1,
 'per_page': 100,
 'groups_count': None}

In [276]:
BASE_URL = "https://api.openalex.org/works"
BASE_KEYWORD = '("child")'
KEYWORDS_DATA = "('math app' OR 'math apps')"
# QUERY = f'{BASE_URL}?search=(abstract:{KEYWORDS_DATA} AND abstract:{BASE_KEYWORD}) OR (title:{KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
QUERY = f'{BASE_URL}?search=(title:{KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
response = requests.get(f"{QUERY}&per-page=100")
j=-1
response.json()['meta']

{'count': 1355,
 'db_response_time_ms': 103,
 'page': 1,
 'per_page': 100,
 'groups_count': None}

In [375]:
BASE_KEYWORD = '("math")'
KEYWORDS_DATA = '("apps")'
# QUERY = f'{BASE_URL}?search=(abstract:{KEYWORDS_DATA} AND abstract:{BASE_KEYWORD}) OR (title:{KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
QUERY = f'{BASE_URL}?search=(title:{KEYWORDS_DATA} AND title:{BASE_KEYWORD})'
response = requests.get(f"{QUERY}&per-page=100")
j=-1
response.json()['meta']

{'count': 3217,
 'db_response_time_ms': 287,
 'page': 1,
 'per_page': 100,
 'groups_count': None}

In [381]:
j+=1
_id = response.json()['results'][j]['id']
print(_id)
print(response.json()['results'][j]['publication_year'])
print(response.json()['results'][j]['title'])

https://openalex.org/W2798796321
2017
From hypertext to hyperdimension Neptunia: The future of VR visual novels: The potentials of new technologies for branching-path narrative games

In [61]:
latest_df.query("id == @_id")

Empty DataFrame
Columns: [id, title, abstract, text]
Index: []

In [74]:
query = "https://api.openalex.org/works?search=(abstract:(child OR infant OR baby OR prenatal OR pregnancy OR toddler OR family OR parent OR pupil) AND abstract:(chatgpt OR income OR 'early childhood education' OR 'artificial intelligence' OR assess OR assessment OR 'augmented reality' OR autism OR behaviour OR development OR 'eye tracking' OR genetics OR income OR learning OR 'learning environment' OR monitor OR psychotherapy OR 'randomised controlled trials' OR robotics OR 'social media' OR 'social services' OR 'special need' OR technology OR 'virtual reality' OR wearable OR app OR apps OR mobile OR math OR maths OR literacy OR reading OR read OR language OR communication OR 'machine learning' OR 'deep learning' OR 'generative ai' OR speech)) OR (title:(child OR infant OR baby OR prenatal OR pregnancy OR toddler OR family OR parent OR pupil) AND title:(chatgpt OR income OR 'early childhood education' OR 'artificial intelligence' OR assess OR assessment OR 'augmented reality' OR autism OR behaviour OR development OR 'eye tracking' OR genetics OR income OR learning OR 'learning environment' OR monitor OR psychotherapy OR 'randomised controlled trials' OR robotics OR 'social media' OR 'social services' OR 'special need' OR technology OR 'virtual reality' OR wearable OR app OR apps OR mobile OR math OR maths OR literacy OR reading OR read OR language OR communication OR 'machine learning' OR 'deep learning' OR 'generative ai' OR speech))"

In [288]:
response = requests.get(f"{query}&per-page=20&filter=publication_year:2021,type:article")
response.json()['meta']

{'count': 5938,
 'db_response_time_ms': 1300,
 'page': 1,
 'per_page': 20,
 'groups_count': None}

In [365]:
TECH_KEYWORDS = '("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")'
CHILD_KEYWORDS = '("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents")'
query2 = f'https://api.openalex.org/works?search=(abstract:{CHILD_KEYWORDS} AND abstract:{TECH_KEYWORDS}) OR (title:{CHILD_KEYWORDS} AND title:{TECH_KEYWORDS})'

In [370]:
response = requests.get(f"{query2}&filter=publication_year:>2016,type:article")
response.json()['meta']

{'count': 901273,
 'db_response_time_ms': 1713,
 'page': 1,
 'per_page': 20,
 'groups_count': None}

In [317]:
j=-1

In [338]:
j+=1
_id = response.json()['results'][j]['id']
print(_id)
print(response.json()['results'][j]['publication_year'])
print(response.json()['results'][j]['title'])

IndexError: list index out of range

In [154]:
response = requests.get(f"{query2}&per-page=20&filter=publication_year:>2012,type:article")
response.json()['meta']

{'count': 1402816,
 'db_response_time_ms': 2651,
 'page': 1,
 'per_page': 20,
 'groups_count': None}

In [131]:
j = 19
_id = response.json()['results'][j]['id']
print(_id)
print(response.json()['results'][j]['publication_year'])
print(response.json()['results'][j]['title'])

https://openalex.org/W3207107988
2021
Perfluoroalkyl substances exposure and immunity, allergic response, infection, and asthma in children: review of epidemiologic studies

In [289]:
CHILD_KEYWORDS_WRONG = "(child OR infant OR baby OR prenatal OR pregnancy OR toddler OR family OR parent OR pupil OR children OR babies OR toddlers OR families OR parents)"

TECH_KEYWORDS_WRONG = '(chatgpt OR income OR "early childhood education" OR "artificial intelligence" OR assess OR assessment OR "augmented reality" OR autism OR behaviour OR development OR "eye tracking" OR genetics OR income OR learning OR "learning environment" OR monitor OR psychotherapy OR "randomised controlled trials" OR robotics OR "social media" OR "social services" OR "special need" OR technology OR "virtual reality" OR wearable OR app OR apps OR mobile OR math OR maths OR literacy OR reading OR read OR language OR communication OR "machine learning" OR "deep learning" OR "generative ai" OR speech)'

query_wrong = f'https://api.openalex.org/works?search=(abstract:{CHILD_KEYWORDS_WRONG} AND abstract:{TECH_KEYWORDS_WRONG}) OR (title:{CHILD_KEYWORDS_WRONG} AND title:{TECH_KEYWORDS_WRONG})'

In [290]:
response = requests.get(f"{query_wrong}&per-page=20&filter=publication_year:2021,type:article")
response.json()['meta']

{'count': 94617,
 'db_response_time_ms': 1536,
 'page': 1,
 'per_page': 20,
 'groups_count': None}

In [291]:
j=-1

In [313]:
j+=1
_id = response.json()['results'][j]['id']
print(_id)
print(response.json()['results'][j]['publication_year'])
print(response.json()['results'][j]['title'])

IndexError: list index out of range

In [342]:
from discovery_child_development.utils import openalex_utils
import importlib
importlib.reload(openalex_utils);
from discovery_child_development import S3_BUCKET, config

In [343]:
API_ROOT = config["openalex_keywords_api_root"]
KEYWORDS = config["openalex_keywords"]
YEARS = config["openalex_years"]

In [395]:
list(range(2017,2024))

[2017, 2018, 2019, 2020, 2021, 2022, 2023]

In [347]:
API_ROOT

'https://api.openalex.org/works?search=(abstract:(child OR infant OR baby OR prenatal OR pregnancy OR toddler OR family OR parent OR pupil) AND abstract:(KEYWORD)) OR (title:(child OR infant OR baby OR prenatal OR pregnancy OR toddler OR family OR parent OR pupil) AND title:(KEYWORD))'

In [403]:
TECH_KEYWORDS = '("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")'
CHILD_KEYWORDS = '("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils")'
QUERY = f'https://api.openalex.org/works?search=(abstract:{CHILD_KEYWORDS} AND abstract:{TECH_KEYWORDS}) OR (title:{CHILD_KEYWORDS} AND title:{TECH_KEYWORDS})'
QUERIES = [f"{QUERY}&filter=publication_year:{year},type:article" for year in YEARS]

In [405]:
QUERIES

['https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2013,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2014,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2015,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2016,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2017,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2018,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2019,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2020,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2021,type:article',
 'https://api.openalex.org/works?search=(abstract:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND abstract:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech")) OR (title:("child" OR "infant" OR "baby" OR "prenatal" OR "pregnancy" OR "toddler" OR "family" OR "parent" OR "pupil" OR "children" OR "babies" OR "toddlers" OR "families" OR "parents" OR "pupils") AND title:("chatgpt" OR "income" OR "early childhood education" OR "artificial intelligence" OR "assess" OR "assessment" OR "augmented reality" OR "autism" OR "behaviour" OR "behavior" OR "development" OR "eye tracking" OR "genetics" OR "income" OR "learning" OR "learning environment" OR "monitor" OR "psychotherapy" OR "randomised controlled trials" OR "robotics" OR "social media" OR "social services" OR "special need" OR "technology" OR "virtual reality" OR "wearable" OR "wearables" OR "app" OR "apps" OR "mobile" OR "math" OR "maths" OR "literacy" OR "reading" OR "read" OR "language" OR "communication" OR "machine learning" OR "deep learning" OR "generative ai" OR "speech"))&filter=publication_year:2022,type:article',

In [404]:
response = requests.get(f"{QUERY}&filter=publication_year:>2016,type:article")
response.json()['meta']

{'count': 925595,
 'db_response_time_ms': 3541,
 'page': 1,
 'per_page': 25,
 'groups_count': None}

In [389]:
response = requests.get(f"{QUERY}&filter=publication_year:{year},type:article" for year in YEARS)
response.json()['meta']

{'count': 93609,
 'db_response_time_ms': 1901,
 'page': 1,
 'per_page': 25,
 'groups_count': None}

In [4]:
import json
from discovery_child_development import PROJECT_DIR

In [5]:
from discovery_child_development.utils import openalex_utils

In [6]:
import pandas as pd

In [12]:
for i in [0, 1, 2, 3, 4, 5, 6]:
    data = json.load(open(PROJECT_DIR / f'inputs/data/openalex_keywords/json/output_{i}.json'))
    data_df = pd.DataFrame(data)

    _data_df = (
        data_df[['id', 'publication_year', 'title', 'abstract_inverted_index', 'authorships', 'language']]
        .dropna(subset=['abstract_inverted_index'])
        .dropna(subset=['title'])
        .query("language == 'en'")
        .assign(abstract = lambda df: df.abstract_inverted_index.apply(openalex_utils.deinvert_abstract))
        .drop(columns=['abstract_inverted_index'])
    )

    _data_df.to_parquet(PROJECT_DIR / f'inputs/data/openalex_keywords/parquet/output_{i}.parquet', index=False)

UndefinedVariableError: name 'language' is not defined

In [4]:
# # Example of chunking
# import numpy as np
# chunk_size = 10000  # Adjust the chunk size based on your data
# # Split DataFrame into chunks and save each chunk separately
# num_chunks = int(np.ceil(len(data_df) / chunk_size))

# for i in range(num_chunks):
#     print(f"Processing chunk {i+1}/{num_chunks}")
#     chunk = data_df[i*chunk_size:(i+1)*chunk_size]
#     chunk.to_parquet(f'output_4_chunk_{i}.parquet')

Processing chunk 1/17