# Combine datasets
- combine tables for Atlas
- combine trends tables for plots

In [19]:
from discovery_child_development import PROJECT_DIR
import pandas as pd
import ast

## Raw data for Atlas

In [93]:
gtr_df = pd.read_csv(PROJECT_DIR / "outputs/data/tables/gtr_final.csv").assign(dataset = 'ukri', country_code='GB')

In [104]:
openalex_df = (
    pd.read_csv(PROJECT_DIR / "outputs/data/tables/openalex_final.csv")
)

In [91]:
patents_df = pd.read_csv(PROJECT_DIR / "outputs/data/tables/patents_final.csv")

In [107]:
combined_df = pd.concat([
    gtr_df,
    openalex_df,
    patents_df,
], ignore_index=True)[['dataset', 'id', 'url', 'text', 'year', 'country_code', 'topic', 'minor_category', 'major_category', 'topic_code', 'amount', 'lead_funder']]

In [108]:
combined_df.to_csv(PROJECT_DIR / "outputs/data/tables/combined_gtr_openalex_patents_final.csv", index=False)

## Data for detailed application plots

In [130]:
import utils
topics_df = utils.load_topic_data()

In [140]:
# applications_gtr_df = pd.read_csv(PROJECT_DIR / 'outputs/data/tables/tech_applications_gtr_amount.csv')
# applications_crunchbase_df = pd.read_csv(PROJECT_DIR / 'outputs/data/tables/tech_applications_crunchbase_amount.csv')

applications_gtr_df = pd.read_csv(PROJECT_DIR / 'outputs/data/tables/tech_applications_gtr_counts.csv')
applications_crunchbase_df = pd.read_csv(PROJECT_DIR / 'outputs/data/tables/tech_applications_crunchbase_counts.csv')

applications_openalex_df = pd.read_csv(PROJECT_DIR / 'outputs/data/tables/tech_applications_openalex.csv')
applications_patents_df = pd.read_csv(PROJECT_DIR / 'outputs/data/tables/tech_applications_patents.csv')

In [141]:
base_df = (
    applications_openalex_df
    .merge(topics_df[['type', 'name']], on='name')
    .sort_values(['type', 'Total'], ascending=[True, False])
)[['type', 'name']]

applications_gtr_df = (
    base_df
    .merge(applications_gtr_df, on='name', how='left').fillna(0)
)

applications_crunchbase_df = (
    base_df
    .merge(applications_crunchbase_df, on='name', how='left').fillna(0)
)

applications_openalex_df = (
    base_df
    .merge(applications_openalex_df, on='name', how='left').fillna(0)
)

applications_patents_df = (
    base_df
    .merge(applications_patents_df, on='name', how='left').fillna(0)
)

In [143]:
applications_patents_df

,type,name,Total,AI,Internet,Mobile,Immersive tech
0,Biosciences,Neuroscience,84.0,75.0,0.0,14.0,13.0
1,Biosciences,Genetics,1.0,1.0,0.0,0.0,0.0
2,Child care & preschool,Preschool,95.0,28.0,2.0,36.0,50.0
3,Child care & preschool,Operations,12.0,6.0,1.0,3.0,9.0
4,Development & learning,Cognitive development,12.0,5.0,0.0,4.0,4.0
5,Development & learning,Communication and language,31.0,18.0,0.0,10.0,7.0
6,Development & learning,Personal social emotional,1.0,1.0,0.0,1.0,0.0
7,Development & learning,Special educational needs,37.0,33.0,0.0,4.0,8.0
8,Development & learning,Mathematics,29.0,12.0,1.0,12.0,9.0
9,Development & learning,Literacy,20.0,8.0,0.0,14.0,3.0
10,Health,Health,121.0,99.0,0.0,11.0,35.0
11,Health,Prenatal,43.0,37.0,0.0,7.0,4.0
12,Health,Nutrition and weight,12.0,8.0,0.0,3.0,1.0
13,Health,Mental health,3.0,2.0,0.0,0.0,1.0
14,Health,Physical development,161.0,69.0,0.0,31.0,95.0
15,Health,Sleep,430.0,316.0,0.0,118.0,109.0
16,Health,Oral health,15.0,11.0,0.0,3.0,1.0
17,Health,Child protection,30.0,24.0,0.0,5.0,11.0
18,Parenting,Parenting,5.0,4.0,0.0,1.0,2.0
19,Society,Social services,2.0,0.0,0.0,2.0,0.0
20,Society,Inequalities,0.0,0.0,0.0,0.0,0.0
21,Society,Community,0.0,0.0,0.0,0.0,0.0
22,Society,Inclusion,0.0,0.0,0.0,0.0,0.0
23,Society,Labour market,0.0,0.0,0.0,0.0,0.0
24,Society,Income,0.0,0.0,0.0,0.0,0.0

In [125]:
applications_patents_df

,type,name,Total,AI,Internet,Mobile,Immersive tech
0,Biosciences,Neuroscience,84.0,75.0,0.0,14.0,13.0
1,Biosciences,Genetics,1.0,1.0,0.0,0.0,0.0
2,Child care & preschool,Preschool,95.0,28.0,2.0,36.0,50.0
3,Child care & preschool,Operations,12.0,6.0,1.0,3.0,9.0
4,Development & learning,Cognitive development,12.0,5.0,0.0,4.0,4.0
5,Development & learning,Communication and language,31.0,18.0,0.0,10.0,7.0
6,Development & learning,Personal social emotional,1.0,1.0,0.0,1.0,0.0
7,Development & learning,Special educational needs,37.0,33.0,0.0,4.0,8.0
8,Development & learning,Mathematics,29.0,12.0,1.0,12.0,9.0
9,Development & learning,Literacy,20.0,8.0,0.0,14.0,3.0
10,Health,Health,121.0,99.0,0.0,11.0,35.0
11,Health,Prenatal,43.0,37.0,0.0,7.0,4.0
12,Health,Nutrition and weight,12.0,8.0,0.0,3.0,1.0
13,Health,Mental health,3.0,2.0,0.0,0.0,1.0
14,Health,Physical development,161.0,69.0,0.0,31.0,95.0
15,Health,Sleep,430.0,316.0,0.0,118.0,109.0
16,Health,Oral health,15.0,11.0,0.0,3.0,1.0
17,Health,Child protection,30.0,24.0,0.0,5.0,11.0
18,Society,Social services,2.0,0.0,0.0,2.0,0.0
19,Society,Inequalities,0.0,0.0,0.0,0.0,0.0
20,Society,Community,0.0,0.0,0.0,0.0,0.0
21,Society,Inclusion,0.0,0.0,0.0,0.0,0.0
22,Society,Labour market,0.0,0.0,0.0,0.0,0.0
23,Society,Income,0.0,0.0,0.0,0.0,0.0